* AutoWater irrigation system

** What is this
This project is an irrigation controller that runs on the esp32. It connects to your wifi network, and hosts a webserver to control the controller (ha ha).

This irrigation controller can run 4 stations. Each station can run up to 4 times a day. If you need more, the code should be easy to change (in theory). If you don't want it to run 4 times a day, set start time and stop time to 00:00.

The web frontend is as good as it is.

** TODO how build it
*** pio run -t upload
*** pio run -t uploadfs

** status of the project
Todo.org has the goodies in it.

** questions?
If you have any questions, you can message me using email. /alanwedel19@gmail.com/

* Make it look more importaint than it really is
** disclaimer
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

* Status of the project
As of 1/29/24 I have it all working. I am not actually using it yet. The web frontend needs a little help, (looks great in firefox, but not chrome. So use firefox :) ).
